### ISSUE TITLE
이수학점 불러오기 실패하는 버그

### ISSUE THREAD

**Issue by tpdns90321** [s-owl/skhu-backend#44]
<img width="471" alt="스크린샷 2019-06-26 오후 1 17 56" src="https://user-images.githubusercontent.com/10331327/60150761-fe9d4b80-9814-11e9-8aa8-626556375e42.png">

파싱 실패하고 있는 듯 하다.

**Comment by sukso96100** [comment]
학과에서 학부제로 개편하면서 이수학점부분 레이아웃이 달라져서 그런듯. 변경된 레이아웃에 맞춰서 수정작업을 해야함. 백엔드랑 앱쪽 둘 다.

**Comment by tpdns90321** [comment]
전공제인 사람과 학부제인 사람 둘 다 고려해야합니까?

**Comment by sukso96100** [comment]
포레스트상에서 레이아웃 어떻게 나온는지가 중요할듯. 전공제 학부제에 따라 다르게 나오는지부터 봐야함

**Comment by sukso96100** [comment]
![SmartSelectImage_2019-06-26-13-31-15](https://user-images.githubusercontent.com/1916739/60151186-bc750980-9816-11e9-9adf-73b4835d3aa0.png)
난 학과젠데 이렇게 나옴
